version: 0.2
env:
  variables:
    PROJECT_HOME: $CODEBUILD_SRC_DIR
    PROJECT_TEST: "$CODEBUILD_SRC_DIR"
    key: "value"

phases:
  pre_build:
    commands:
      - chmod +x scripts/setup.sh
  build:
    commands:
      - ls
      - ./scripts/setup.sh
